### ISSUE TITLE
finished CTFs still showing under Import

### ISSUE THREAD

**Issue by lanjelot** [hugsy/ctfpad#15]
Is this because `@lru_cache` makes `ctftime_fetch_running_ctf_data()` return old events at https://github.com/hugsy/ctfpad/blob/master/ctfpad/views/ctfs.py#L33?

**Comment by hugsy** [comment]
Likely. 

But we need some caching here, fetching data from ctftime is a too long operation not to be cached.

**Comment by lanjelot** [comment]
Can we lower the TTL at all? Or rather what we should do is filter out ctfs that have ended. I'll look into it.

**Comment by hugsy** [comment]
You can flush the cache but then there's no point.

We can always hide (or add a notation to) the CTF already finished.
