### ISSUE TITLE
The toolbar disappear when I visit a challenge page after the first time.

### ISSUE THREAD

**Issue by DaniloNC** [hugsy/ctfpad#25]
The toolbar disappear when I visit a challenge page for the second time. 

Toolbar present on my first access:
![image](https://user-images.githubusercontent.com/405967/106371685-c2a16500-632c-11eb-87e1-0e84f1b3f046.png)

Toolbar not present on the second time accessing the page:
![image](https://user-images.githubusercontent.com/405967/106371703-fed4c580-632c-11eb-84f0-64c1c7a1a1c1.png)

**Comment by hugsy** [comment]
Need more info (browser ? version ?) but it looks to me it's a bug in hedgedoc not ctfpad. ctfpad does just iframe hedgedoc

**Comment by hofill** [comment]
I also have this, how did you fix it?

**Comment by hugsy** [comment]
Add `?both` 
Although this should be [fixed now](https://github.com/hugsy/ctfpad/blob/69ee3524cff0615417e65b92b3999477a886f026/ctfpad/templates/ctfpad/challenges/detail.html#L79)

**Comment by hofill** [comment]
> Add `?both` Although this should be [fixed now](https://github.com/hugsy/ctfpad/blob/69ee3524cff0615417e65b92b3999477a886f026/ctfpad/templates/ctfpad/challenges/detail.html#L79)

I tried to add ?both, (http://url.com:8080/#/ctf/1-ctf/task/15-core-problems?both#) but the page didn't change at all for me. I still went to the normal view.
I'm using the latest version of Firefox, but I've also tried it on Chrome.
Also tried refreshing.

Another thing that could be the issue (IMO) would be me not using ssl?

**Comment by hugsy** [comment]
Your URL is incorrect (you have 2 `#`). 
SSL is not a strict requirement, as long as you have all apps at the same level (all SSL or none SSL). I'd recommend using  `docker-compose` (after customizing it to your own environment of course). It works perfectly this way - without or with SSL (I use letsencrypt for it, no problem).
