### ISSUE TITLE
Replace `rofl256/whiteboard` with `excalidraw/excalidraw`

### ISSUE THREAD

**Issue by hugsy** [hugsy/ctfpad#53]
Just need to change the link to `http://server/#room={room_id},{room_key}`

Where `room_id` format is `[0-9a-f]{20}` and `room_key` format is `[a-zA-Z0-9_-]{22}`

**Comment by gcalmettes** [comment]
Hello,
Thank you for `ctfpad`!
If you're still interested in replacing the current whiteboard solution with `excalidraw`, I actually have a working prototype based on a self-hosted `excalidraw` (leveraging [excalidraw-storage-backend](https://gitlab.com/kiliandeca/excalidraw-storage-backend) to prevent having to rely on google firebase).
Happy to propose a PR if this is still in your roadmap.

**Comment by hugsy** [comment]
Sure, a PR would be welcome
