### ISSUE TITLE
DOS of main page by setting only end date in CTF

### ISSUE THREAD

**Issue by vanFrZy** [hugsy/ctfpad#56]
When creating a CTF and setting no dates and then updating the CTF and setting only an END date causes the server to crash and any page displaying the CTF with the status is unavailable.

**Comment by hugsy** [comment]
I cannot reproduce, can you enable the debug mode and provide traces (screenshot, callstack)?

**Comment by hugsy** [comment]
Fixed by [b3a6c73](https://github.com/hugsy/ctfhub/pull/81/commits/b3a6c73a01464c0be81dc2cdc58d7b410b6f1367)
