### ISSUE TITLE
Better marketing

### ISSUE THREAD

**Issue by hugsy** [hugsy/ctfpad#60]
Too many conflicts with existing ones.

Also choose a logo.

**Comment by h4ckd0tm3** [comment]
Are you talking about a rename?

**Comment by hugsy** [comment]
Yes, suggestions?

**Comment by h4ckd0tm3** [comment]
One that would be funny is "FlagHoarder" there would be no reference to the note taking however.

**Comment by hugsy** [comment]
![image](https://github.com/hugsy/ctfpad/assets/590234/e5233616-595d-49ff-ab87-89649602d9fa)

I'm kindda leaning towards **CTFHub**, short, simple, catchy. Thoughts?

**Comment by hugsy** [comment]
Found possible logos
 
![ctfhub](https://github.com/hugsy/ctfpad/assets/590234/6bbbef2a-5e70-43bf-8546-1bcc27cd8b2f)

![image](https://github.com/hugsy/ctfpad/assets/590234/2f27eee8-da00-4bf3-b7c5-6d52874f26b2)

![image](https://github.com/hugsy/ctfpad/assets/590234/38591b25-a32f-4124-b880-956d9f0a7ddd)

**Comment by h4ckd0tm3** [comment]
If you go for CTFHub the Logo kinda has to be orange and black ( ˘ ͜ʖ ˘)
