### ISSUE TITLE
JS Code Cleanup

### ISSUE THREAD

**Issue by hugsy** [hugsy/ctfpad#73]
* https://github.com/hugsy/ctfpad/pull/72/files#r1234280698
 * https://github.com/hugsy/ctfpad/pull/72/files#r1234283378

**Comment by h4ckd0tm3** [comment]
Bumped Chart.js already and fixed all errors. Opening a PR for a bunch of things later.

**Comment by hugsy** [comment]
You're a machine!

**Comment by hugsy** [comment]
for tracking : #75

**Comment by hugsy** [comment]
Closing since #85 was merged with the changes

**Comment by hugsy** [comment]
Credits to @h4ckd0tm3
